version: '3.8'

services:
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DEBUG=True
      - DB_NAME=readerDataBase
      - DB_USER=READER
      - DB_PASSWORD=qwerty123
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=readerDataBase
      - POSTGRES_USER=READER
      - POSTGRES_PASSWORD=qwerty123

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data: